### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by fonsleenaars** [forgeworks/quill-delta-python#1]
Thanks for building this, it perfectly matches a use case I have for it.

Could you publish this to PyPi so I can `pip install` the package? That would save on some dependency management and I'm sure there's more people using Quill/Deltas that would love to use this!

**Comment by DeadWisdom** [comment]
Yep, will do!

**Comment by anschutz** [comment]
Any update on this?

**Comment by rtaft** [comment]
Please publish this.  I only see one similar project on pypi and its failing it's own unit tests.

**Comment by gdude2002** [comment]
This really should be published, @DeadWisdom - other packages cannot rely on git or URL dependencies. PyPi will reject them.

**Comment by mnagy** [comment]
I'm adding my voice here, too. This package is exactly what I was looking for, it would be pretty neat if it was on PyPI :) :+1:

**Comment by DeadWisdom** [comment]
Sorry to delay on this all, it's done!

    > pip install quill-delta[html]
