### ISSUE TITLE
Alignment does not work for video block

### ISSUE THREAD

**Issue by sebammon** [forgeworks/quill-delta-python#9]
Using centre, or right alignment does not work for the video block.

The class `ql-align-*` is not applied to the iframe element of the video block. See screenshot below:

**In the editor:**
<img width="631" alt="Screenshot 2020-10-12 at 13 01 53" src="https://user-images.githubusercontent.com/50615191/95710594-2f63f700-0c8b-11eb-9ffb-6ccba02a189a.png">

**Rendered from quill-delta-python**
<img width="480" alt="Rendered" src="https://user-images.githubusercontent.com/50615191/95710670-5fab9580-0c8b-11eb-8d5e-cafaaef0113b.png">

_P.S. Would you mind if I attempt to create a PR with the fix?_

**Comment by DeadWisdom** [comment]
Would not mind, please do! @sebammon

**Comment by DeadWisdom** [comment]
Make sure you make a test, as well.

**Comment by sebammon** [comment]
@DeadWisdom I could use some advice... Unlike the block formats where the elements are changed by the attrs of the endline, the video's alignment is set in the insert e.g.:
```python
{"insert": {"video": "https://www.youtube.com/embed/NAb9V08zcBE"}, "attributes": { "align": "center" }}
```

Should I apply the fix in the function
```python
@format
def video(root, op):
...
```
or am I missing something else?

**Comment by sebammon** [comment]
Fix would look like this:
```python
@format
def video(root, op):
    attributes = op.get('attributes', {})
    iframe = root.makeelement('iframe')
    iframe.attrib.update({
        'class': VIDEO_IFRAME_CLASS,
        'frameborder': '0',
        'allowfullscreen': 'true',
        'src': op['insert']['video']
    })
    if isinstance(attributes, dict) and attributes.get('align', None):
        align_block(iframe, attributes)
    root.addprevious(iframe)
    return iframe
```

**Comment by DeadWisdom** [comment]
Yeah, that's right. We can access the attributes for that reason.

**Comment by sebammon** [comment]
@DeadWisdom I have created a PR. Please can you review it :)
